spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_yababjo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1516
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
